'''
Created on Mar 6, 2019

@author: filipe
'''
import os, csv, sys

class util(object):
    '''
    classdocs
    '''
    @staticmethod
    def get_path(directoryName):
        path = os.path.dirname(sys.argv[0])
        if not path:
            path = '.'
        composed_path = os.path.join(path, directoryName)
        return composed_path
    
    @staticmethod
    def read_csv(dirName, fileName):
        dirPath = util.get_path(dirName)
        file = open(os.path.join(dirPath, fileName))
        students = csv.reader(file)
        header = next(students, None)
        column = {}
        for h in header:
                column[h] = []
        for student in students:
            for h, v in zip(header, student):
                column[h].append(v)
        file.close
        return column
    @staticmethod
    
    def extract_foundsimilarities(dirName="rubric", fileName="autogeneratedrubric.csv"):
        tokens_paths = util.get_path(dirName)
        completeName = os.path.join(tokens_paths, fileName)
        with open(completeName) as f:
            reader = csv.reader(f)
            alltokens = list(reader)
        f.close()
        del alltokens[0]
        return alltokens

    def __init__(self, params):
        '''
        Constructor
        '''
        